/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TauriExampleRouteImport } from './routes/tauri-example'
import { Route as IndexRouteImport } from './routes/index'

const TauriExampleRoute = TauriExampleRouteImport.update({
  id: '/tauri-example',
  path: '/tauri-example',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tauri-example': typeof TauriExampleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tauri-example': typeof TauriExampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tauri-example': typeof TauriExampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tauri-example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tauri-example'
  id: '__root__' | '/' | '/tauri-example'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TauriExampleRoute: typeof TauriExampleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tauri-example': {
      id: '/tauri-example'
      path: '/tauri-example'
      fullPath: '/tauri-example'
      preLoaderRoute: typeof TauriExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TauriExampleRoute: TauriExampleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
