/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorePersistanceRouteImport } from './routes/store-persistance'
import { Route as RustFunctionRouteImport } from './routes/rust-function'
import { Route as IndexRouteImport } from './routes/index'

const StorePersistanceRoute = StorePersistanceRouteImport.update({
  id: '/store-persistance',
  path: '/store-persistance',
  getParentRoute: () => rootRouteImport,
} as any)
const RustFunctionRoute = RustFunctionRouteImport.update({
  id: '/rust-function',
  path: '/rust-function',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rust-function': typeof RustFunctionRoute
  '/store-persistance': typeof StorePersistanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rust-function': typeof RustFunctionRoute
  '/store-persistance': typeof StorePersistanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rust-function': typeof RustFunctionRoute
  '/store-persistance': typeof StorePersistanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rust-function' | '/store-persistance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rust-function' | '/store-persistance'
  id: '__root__' | '/' | '/rust-function' | '/store-persistance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RustFunctionRoute: typeof RustFunctionRoute
  StorePersistanceRoute: typeof StorePersistanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-persistance': {
      id: '/store-persistance'
      path: '/store-persistance'
      fullPath: '/store-persistance'
      preLoaderRoute: typeof StorePersistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rust-function': {
      id: '/rust-function'
      path: '/rust-function'
      fullPath: '/rust-function'
      preLoaderRoute: typeof RustFunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RustFunctionRoute: RustFunctionRoute,
  StorePersistanceRoute: StorePersistanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
